/** Prisma `select` slice for {@link hasTrainerFullPlatformAccess}. */
export const trainerFullAccessProfileSelect = {
  hasSignedTOS: true,
  hasUploadedW9: true,
  backgroundCheckStatus: true,
  backgroundCheckClearedAt: true,
  onboardingTrackCpt: true,
  onboardingTrackNutrition: true,
  onboardingTrackSpecialist: true,
  certificationReviewStatus: true,
  nutritionistCertificationReviewStatus: true,
  specialistCertificationReviewStatus: true,
  limitedDashboardUnlockedAt: true,
  registrationFeeHoldStatus: true,
  hasPaidRegistrationFee: true,
  dashboardActivatedAt: true,
  complianceWindowStartedAt: true,
  complianceWindowPausedAt: true,
  complianceCertReuploadDeadlineAt: true,
  complianceHumanReviewDeadlineAt: true,
  complianceCertFailedAttempts: true,
  complianceWindowExpiredAt: true,
  checkrReportId: true,
  fitHubPromoEndsAt: true,
} as const;
