import type { TransactionalEmailKind } from "@/lib/transactional-email-kinds";
import type { TransactionalEmailTemplateFields } from "@/lib/transactional-email-template-types";

const STANDARD_CTA = (label: string, hrefKey: string): Pick<TransactionalEmailTemplateFields, "ctaLabel" | "ctaHrefKey" | "layout"> => ({
  ctaLabel: label,
  ctaHrefKey: hrefKey,
  layout: { type: "standard", ctaHrefKey: hrefKey },
});

const DEFAULTS: Record<TransactionalEmailKind, TransactionalEmailTemplateFields> = {
  CLIENT_WELCOME: {
    subject: "Welcome to Match Fit",
    preheader: "Your Match Fit account is ready.",
    title: "Welcome aboard",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — thanks for joining Match Fit.',
      "Discover coaches, book sessions, and keep everything in one place.",
    ],
    textBody: "Hi {{firstName}},\n\nThanks for joining Match Fit. Open your dashboard to find coaches and manage your training:\n{{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open dashboard", "dashboardUrl"),
  },
  TRAINER_WELCOME: {
    subject: "Welcome to Match Fit — coach account",
    preheader: "Your coach workspace is ready.",
    title: "Welcome, coach",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — your Match Fit trainer profile is set up.',
      "Complete compliance steps in the dashboard when prompted, then turn on discovery so clients can find you.",
    ],
    textBody: "Hi {{firstName}},\n\nYour trainer account is live. Finish onboarding tasks in the dashboard, then start connecting with clients.\n{{trainerDashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Trainer dashboard", "trainerDashboardUrl"),
  },
  OTP_2FA: {
    subject: "Your Match Fit verification code",
    preheader: "Your code is {{code}}.",
    title: "Verification code",
    bodyParagraphs: [
      "Enter this code to continue signing in to Match Fit:",
      "Expires in 10 minutes. If this was not you, secure your password in settings.",
    ],
    textBody: "Your verification code is: {{code}}\n\nIt expires in 10 minutes. If you did not try to sign in, ignore this email.",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "otp", codeKey: "code" },
  },
  PASSWORD_RESET: {
    subject: "Reset your Match Fit password",
    preheader: "Password reset requested.",
    title: "Reset your password",
    bodyParagraphs: [
      "We received a request to reset the password on your Match Fit account.",
      "The button below expires in about an hour. If you did not request this, you can ignore this message.",
    ],
    textBody: "We received a request to reset the password for your Match Fit account.\n\nOpen this link (valid for 1 hour):\n{{resetUrl}}\n\nIf you did not request this, you can ignore this email.",
    ...STANDARD_CTA("Reset password", "resetUrl"),
  },
  EMAIL_CHANGE_CONFIRM: {
    subject: "Confirm your new Match Fit email",
    preheader: "Confirm your new email address.",
    title: "Confirm new email",
    bodyParagraphs: ["Tap the button to verify this inbox for your Match Fit account."],
    textBody: "Confirm this email address for your Match Fit account:\n{{confirmUrl}}\n\nLink expires in 1 hour. If you did not request this, ignore this email.",
    ...STANDARD_CTA("Confirm email", "confirmUrl"),
  },
  EMAIL_CHANGE_SECURITY: {
    subject: "Match Fit email change started",
    preheader: "An email change was requested on your account.",
    title: "Email change requested",
    bodyParagraphs: [
      'Someone started using <strong style="color:#E8EAEF">{{newEmail}}</strong> as the new email on your Match Fit account.',
      "If this was you, confirm that inbox from the separate message we sent there. If not, change your password immediately.",
    ],
    textBody: "Someone started changing the email on your Match Fit account to {{newEmail}}.\n\nIf this was you, confirm the new inbox from the message sent there.\n\nIf not you, reset your password and contact support.",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "standard" },
  },
  LOGIN_SECURITY_ALERT: {
    subject: "New sign-in to your Match Fit account",
    preheader: "New activity on your account.",
    title: "New sign-in",
    bodyParagraphs: [
      'Time: <strong style="color:#E8EAEF">{{loginTime}}</strong>',
      "{{deviceLine}} · {{ipLine}}",
      "If this was not you, reset your password from Account settings.",
    ],
    textBody: "We noticed a new sign-in to Match Fit.\n\nWhen: {{loginTime}}\n{{deviceLine}}\n{{ipLine}}\n\nIf this was you, you can ignore this message. If not, reset your password.",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "standard" },
  },
  W9_TAX_VERIFICATION: {
    subject: "Your Match Fit W-9 on file",
    preheader: "W-9 copy from Match Fit.",
    title: "W-9 information",
    bodyParagraphs: [
      "Below is the tax information you asked us to send from your Match Fit coach account.",
      "{{w9Summary}}",
    ],
    textBody: "Your W-9 tax information was emailed as requested.\n\nIf you did not request this copy, change your password and contact support.\n\n{{w9Summary}}",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "standard" },
  },
  CERTIFICATION_RENEWAL_REMINDER: {
    subject: "Renew your {{certName}} on Match Fit",
    preheader: "Credential renewal reminder.",
    title: "Certification renewal",
    bodyParagraphs: [
      'Your <strong style="color:#E8EAEF">{{certName}}</strong> listing should be refreshed before <strong style="color:#E8EAEF">{{expiryDate}}</strong>.',
      "Upload an updated certificate from your trainer dashboard so clients keep full confidence in your profile.",
    ],
    textBody: "Your {{certName}} credential on Match Fit should be renewed before {{expiryDate}}.\n\nUpload an updated document from Trainer settings → Compliance.\n{{trainerDashboardUrl}}",
    ...STANDARD_CTA("Open compliance", "trainerDashboardUrl"),
  },
  BACKGROUND_CHECK_UPDATE: {
    subject: "Background check update — Match Fit",
    preheader: "Background check status changed.",
    title: "Background check",
    bodyParagraphs: [
      'Your screening status is now <strong style="color:#E8EAEF">{{bgStatus}}</strong>.',
      "Open Match Fit for any required follow-up steps.",
    ],
    textBody: "Your background check status on Match Fit is now: {{bgStatus}}.\n\nOpen your dashboard for details.",
    ...STANDARD_CTA("View dashboard", "dashboardUrl"),
  },
  BACKGROUND_CHECK_PLAN_B_INVITE_REQUEST: {
    subject: "[Match Fit] Send Checkr invite — {{trainerName}}",
    preheader: "Trainer needs a Checkr invitation (manual queue).",
    title: "Send Checkr invite",
    bodyParagraphs: [
      'Trainer <strong style="color:#E8EAEF">{{trainerName}}</strong> ({{trainerEmail}}) requested background screening.',
      "Username: {{trainerUsername}} · Phone: {{trainerPhone}} · ZIP: {{serviceZip}}",
      "Send the invite from the Checkr Dashboard, then confirm below so the trainer is notified.",
    ],
    textBody: "A trainer requested a Checkr background screening invitation.\n\nName: {{trainerName}}\nEmail: {{trainerEmail}}\nUsername: {{trainerUsername}}\nPhone: {{trainerPhone}}\nZIP: {{serviceZip}}\nTrainer id: {{trainerId}}\n\nAfter you send the Checkr dashboard invite, confirm here: {{confirmInviteSentUrl}}",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "confirm-button", confirmUrlKey: "confirmInviteSentUrl", confirmLabel: "Background check sent confirmation" },
  },
  BACKGROUND_CHECK_PLAN_B_INVITE_SENT_TRAINER: {
    subject: "Your Checkr background check invitation — Match Fit",
    preheader: "Complete your Checkr screening within 7 days.",
    title: "Checkr invite sent",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — your Checkr invitation is on its way or already in your inbox.',
      "Complete every step Checkr shows you. If you do not finish within 7 days, your invitation may expire and your screening escrow will not apply.",
      "When you are done, open your Match Fit dashboard — we will update your status after results are verified.",
    ],
    textBody: "Hi {{firstName}},\n\nMatch Fit has sent your Checkr background screening invitation.\n1. Open the email from Checkr (check spam).\n2. Complete every disclosure and authorization step.\n3. Submit within 7 days — invitations expire.\n\nDashboard: {{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open compliance", "dashboardUrl"),
  },
  BACKGROUND_CHECK_PLAN_B_REVIEW: {
    subject: "[Match Fit] Background check ready for review — {{trainerName}}",
    preheader: "Approve or deny trainer background screening.",
    title: "Screening review",
    bodyParagraphs: [
      'Review results for <strong style="color:#E8EAEF">{{trainerName}}</strong>.',
      "Report: {{reportId}} · Status: {{status}}",
    ],
    textBody: "A trainer background check needs staff approval.\n\nTrainer: {{trainerName}} ({{trainerEmail}})\nReport id: {{reportId}}\nStatus: {{status}}\n\nApprove: {{approveUrl}}\nDeny: {{denyUrl}}",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "dual-action", approveUrlKey: "approveUrl", denyUrlKey: "denyUrl" },
  },
  ADMIN_REGISTRATION_REQUEST: {
    subject: "[Match Fit] Administrator approval — {{adminName}}",
    preheader: "Administrator onboarding needs review.",
    title: "Admin registration",
    bodyParagraphs: [
      'Applicant: <strong style="color:#E8EAEF">{{adminName}}</strong> ({{adminEmail}})',
      "{{adminNotes}}",
    ],
    textBody: "A new Match Fit administrator request was submitted.\n\nName: {{adminName}}\nEmail: {{adminEmail}}\nNotes: {{adminNotes}}\n\nApprove: {{approveUrl}}\nDeny: {{denyUrl}}",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "dual-action", approveUrlKey: "approveUrl", denyUrlKey: "denyUrl" },
  },
  PURCHASE_CONFIRMATION: {
    subject: "Purchase confirmation — Match Fit",
    preheader: "Your payment went through.",
    title: "Purchase confirmed",
    bodyParagraphs: [
      'You bought <strong style="color:#E8EAEF">{{itemLabel}}</strong> with @{{trainerUsername}}.',
      'Amount: <strong style="color:#E8EAEF">{{amount}}</strong>',
    ],
    textBody: "Thanks for your purchase on Match Fit.\n\n{{itemLabel}}\nAmount: {{amount}}\nCoach: @{{trainerUsername}}\n\nReference: {{referenceId}}",
    ...STANDARD_CTA("View billing", "dashboardUrl"),
  },
  COACH_PACKAGE_SALE: {
    subject: "New package sale — Match Fit",
    preheader: "You have a new paid package.",
    title: "New client sale",
    bodyParagraphs: [
      '@{{clientUsername}} purchased <strong style="color:#E8EAEF">{{itemLabel}}</strong>.',
      'Package amount (before card processing fees): <strong style="color:#E8EAEF">{{amount}}</strong>',
    ],
    textBody: "A client purchased a package from you on Match Fit.\n\nClient: @{{clientUsername}}\n{{itemLabel}}\nCoach service amount (before processing fees): {{amount}}\n",
    ...STANDARD_CTA("Open messages", "trainerDashboardUrl"),
  },
  TRAINER_PAYOUT: {
    subject: "Payout processed — Match Fit",
    preheader: "Payout on the way.",
    title: "Payout sent",
    bodyParagraphs: [
      'We initiated <strong style="color:#E8EAEF">{{payoutAmount}}</strong> for <strong style="color:#E8EAEF">{{periodLabel}}</strong>.',
      "Settlement timing depends on your bank and payout method.",
    ],
    textBody: "A payout of {{payoutAmount}} was initiated for {{periodLabel}}.\n\nFunds timing depends on your bank. See Earnings in the trainer dashboard.",
    ...STANDARD_CTA("View earnings", "trainerDashboardUrl"),
  },
  SUBSCRIPTION_MANAGEMENT_UPDATE: {
    subject: "Subscription update — Match Fit",
    preheader: "Your subscription changed.",
    title: "Subscription update",
    bodyParagraphs: ["{{statusLine}}", "{{detailLine}}"],
    textBody: "Your Match Fit membership changed.\n\n{{statusLine}}\n{{detailLine}}\n{{dashboardUrl}}",
    ...STANDARD_CTA("Manage plan", "dashboardUrl"),
  },
  OFF_PLATFORM_VIOLATION_NOTICE: {
    subject: "Important notice — Match Fit policies",
    preheader: "Policy reminder from Match Fit.",
    title: "Policy notice",
    bodyParagraphs: [
      "{{violationSummary}}",
      "Off-platform payments violate Match Fit policies and can affect account standing.",
    ],
    textBody: "We need to share an update about your Match Fit account.\n\n{{violationSummary}}\n\nReply to this thread or open the app for next steps.",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "standard" },
  },
  BUG_REPORT_ACKNOWLEDGMENT: {
    subject: "We received your bug report",
    preheader: "Bug report logged.",
    title: "Thanks for the report",
    bodyParagraphs: [
      'Reference <strong style="color:#E8EAEF">{{reportId}}</strong> — we logged your feedback.',
      "If we need more detail we will reply from this thread.",
    ],
    textBody: "Thanks for the report (ref {{reportId}}). Our team will review it and follow up if we need more detail.\n\n— Match Fit Support",
    ctaLabel: null,
    ctaHrefKey: null,
    layout: { type: "standard" },
  },
  NEW_CLIENT_INQUIRY: {
    subject: "New client interest — Match Fit",
    preheader: "A client is interested in training with you.",
    title: "New client inquiry",
    bodyParagraphs: [
      "{{inquiryNote}}",
      'Client: <strong style="color:#E8EAEF">@{{clientUsername}}</strong>',
    ],
    textBody: "{{inquiryNote}}\n\nClient: @{{clientUsername}}\nRespond from Profile interests in your trainer dashboard.\n{{interestsUrl}}",
    ...STANDARD_CTA("Review inquiry", "interestsUrl"),
  },
  BOOKING_SESSION_CONFIRMED: {
    subject: "Your session is confirmed — Match Fit",
    preheader: "Confirmed with {{coachName}}.",
    title: "Session confirmed",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — you confirmed a session with <strong style="color:#E8EAEF">{{coachName}}</strong> starting <strong style="color:#E8EAEF">{{startLabel}}</strong>.',
      "Session details and join link appear below when applicable.",
    ],
    textBody: "Hi {{firstName}},\n\nYou confirmed a session with {{coachName}} starting {{startLabel}}.\n\nMessages: {{messagesThreadUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open Messages", "messagesThreadUrl"),
    layout: { type: "booking-session" },
  },
  CONTENT_MODERATION_NOTICE: {
    subject: "Content review — Match Fit",
    preheader: "Your content needs attention.",
    title: "Moderation update",
    bodyParagraphs: ["{{moderationSummary}}"],
    textBody: "{{moderationSummary}}\n\nOpen Match Fit to review any required actions.\n{{trainerDashboardUrl}}",
    ...STANDARD_CTA("Open dashboard", "trainerDashboardUrl"),
  },
  PAYMENT_FAILED: {
    subject: "Payment issue — Match Fit",
    preheader: "Action needed on your account.",
    title: "Payment failed",
    bodyParagraphs: [
      "{{detailLine}}",
      "Update your card or billing details so your membership stays active.",
    ],
    textBody: "We could not process a recent Match Fit payment.\n\n{{detailLine}}\n\nUpdate your payment method in billing settings:\n{{dashboardUrl}}",
    ...STANDARD_CTA("Update billing", "dashboardUrl"),
  },
  POLICY_UPDATE: {
    subject: "Policy update: {{policyName}}",
    preheader: "Please review the updated policy.",
    title: "Policy update",
    bodyParagraphs: [
      'We updated <strong style="color:#E8EAEF">{{policyName}}</strong>.',
      "Continued use of Match Fit after the effective date means you accept the revised terms.",
    ],
    textBody: "Match Fit posted an update to {{policyName}}.\n\nReview it here: {{policyUrl}}",
    ...STANDARD_CTA("Read policy", "policyUrl"),
  },
  BETA_WAITLIST_TRAINER_CONFIRM: {
    subject: "You're on the Match Fit coach waitlist",
    preheader: "Queue position {{queuePosition}}.",
    title: "Waitlist confirmed",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — you\'re on the coach waitlist.',
      'Your place in line: <strong style="color:#E8EAEF">#{{queuePosition}}</strong>. We\'ll send a secure invite link when capacity opens.',
    ],
    textBody: "Hi {{firstName}},\n\nThanks for joining the Match Fit beta waitlist. You're #{{queuePosition}} in line. We'll email you when a slot opens.\n\n— Match Fit",
    ...STANDARD_CTA("Visit Match Fit", "supportUrl"),
  },
  BETA_WAITLIST_CLIENT_CONFIRM: {
    subject: "You're on the Match Fit member waitlist",
    preheader: "Queue position {{queuePosition}}.",
    title: "Waitlist confirmed",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — you\'re on the member waitlist.',
      'Your place in line: <strong style="color:#E8EAEF">#{{queuePosition}}</strong>. We\'ll send a secure invite link when capacity opens.',
    ],
    textBody: "Hi {{firstName}},\n\nThanks for joining the Match Fit beta waitlist. You're #{{queuePosition}} in line. We'll email you when a slot opens.\n\n— Match Fit",
    ...STANDARD_CTA("Visit Match Fit", "supportUrl"),
  },
  BETA_WAITLIST_TRAINER_INVITE: {
    subject: "Your Match Fit coach invite is ready",
    preheader: "Complete sign-up before {{slotExpiresLabel}}.",
    title: "Your invite is ready",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — a coach slot is reserved for you.',
      'Username <strong style="color:#E8EAEF">@{{reservedUsername}}</strong> is held until <strong style="color:#E8EAEF">{{slotExpiresLabel}}</strong>.',
    ],
    textBody: "Hi {{firstName}},\n\nA slot opened. Complete sign-up before {{slotExpiresLabel}}:\n{{joinUrl}}\n\nReserved username: @{{reservedUsername}}\n\n— Match Fit",
    ...STANDARD_CTA("Complete sign-up", "joinUrl"),
  },
  BETA_WAITLIST_CLIENT_INVITE: {
    subject: "Your Match Fit member invite is ready",
    preheader: "Complete sign-up before {{slotExpiresLabel}}.",
    title: "Your invite is ready",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — a member slot is reserved for you.',
      'Username <strong style="color:#E8EAEF">@{{reservedUsername}}</strong> is held until <strong style="color:#E8EAEF">{{slotExpiresLabel}}</strong>.',
    ],
    textBody: "Hi {{firstName}},\n\nA slot opened. Complete sign-up before {{slotExpiresLabel}}:\n{{joinUrl}}\n\nReserved username: @{{reservedUsername}}\n\n— Match Fit",
    ...STANDARD_CTA("Complete sign-up", "joinUrl"),
  },
  CLIENT_MEMBERSHIP_TRIAL_STARTED: {
    subject: "Your Match Fit free trial started",
    preheader: "Your platform trial is active.",
    title: "Trial started",
    bodyParagraphs: [
      'Your Match Fit account includes a <strong style="color:#E8EAEF">{{trialDays}}-day</strong> platform trial.',
      "Manage billing from your dashboard when you are ready to subscribe.",
    ],
    textBody: "Your Match Fit account is active with a {{trialDays}}-day platform trial.\n\nManage billing: {{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open billing", "dashboardUrl"),
  },
  CLIENT_MEMBERSHIP_TRIAL_ENDING: {
    subject: "Your Match Fit Stripe trial ends soon",
    preheader: "Stripe billing begins {{trialEndLabel}}.",
    title: "Stripe trial ending soon",
    bodyParagraphs: [
      'Your Stripe subscription trial ends on <strong style="color:#E8EAEF">{{trialEndLabel}}</strong>.',
      'Unless you cancel, your card on file will be charged <strong style="color:#E8EAEF">${{monthlyUsd}}/month</strong> on that date.',
    ],
    textBody: "Your Stripe subscription trial ends on {{trialEndLabel}}. Unless you cancel, Match Fit will charge ${{monthlyUsd}}/month on that date using the card on file.\n\nManage billing: {{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Manage membership", "dashboardUrl"),
  },
  CLIENT_PLATFORM_PAYMENT_GRACE_STARTED: {
    subject: "Your Match Fit free trial ended — subscribe to keep access",
    preheader: "Subscribe before {{paymentGraceUntilLabel}}.",
    title: "Payment grace started",
    bodyParagraphs: [
      'Your <strong style="color:#E8EAEF">platform free trial</strong> has ended.',
      'You have <strong style="color:#E8EAEF">{{paymentGraceDays}} days</strong> (until <strong style="color:#E8EAEF">{{paymentGraceUntilLabel}}</strong>) to connect a card and start your <strong style="color:#E8EAEF">${{monthlyUsd}}/month</strong> subscription.',
      "If payment is not completed by then, your account is deactivated until you pay to reactivate — a new free trial is not offered.",
    ],
    textBody: "Your platform free trial has ended. Connect a card and subscribe at ${{monthlyUsd}}/month before {{paymentGraceUntilLabel}} ({{paymentGraceDays}}-day payment grace).\n\nSubscribe: {{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Subscribe now", "dashboardUrl"),
  },
  TRAINER_REGISTRATION_FEE_RECEIPT: {
    subject: "Match Fit trainer registration — payment received",
    preheader: "Paid {{amount}}.",
    title: "Payment received",
    bodyParagraphs: [
      'Thank you — we received your trainer registration payment of <strong style="color:#E8EAEF">{{amount}}</strong>.',
      "Your compliance record is updated. Keep your certifications and background check current to stay active.",
    ],
    textBody: "We received your trainer registration payment of {{amount}}.\n\nView compliance: {{trainerDashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Compliance dashboard", "trainerDashboardUrl"),
  },
  TRAINER_DEFERRED_FEE_GRACE_STARTED: {
    subject: "72-hour grace — deferred platform fee — Match Fit",
    preheader: "Clear your deferred balance soon.",
    title: "Grace period started",
    bodyParagraphs: [
      "Your 60-day deferred platform fee window ended with a remaining balance.",
      'You have <strong style="color:#E8EAEF">{{graceHours}} hours</strong> to clear the balance before your account is banned for one year.',
    ],
    textBody:
      "Your deferred platform fee grace period started. You have {{graceHours}} hours to clear your balance.\n\n{{trainerDashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Billing dashboard", "trainerDashboardUrl"),
  },
  TRAINER_DEFERRED_FEE_BANNED: {
    subject: "Account suspended — deferred platform fee — Match Fit",
    preheader: "Your account is suspended.",
    title: "Account suspended",
    bodyParagraphs: [
      "Your deferred platform fee was not cleared during the grace period. Your trainer account is suspended for one year.",
      'Contact <strong style="color:#E8EAEF">{{supportEmail}}</strong> if you believe this is an error.',
    ],
    textBody:
      "Your deferred platform fee was not cleared. Your account is suspended for one year.\n\nSupport: {{supportEmail}}\n\n— Match Fit",
    ...STANDARD_CTA("Trainer dashboard", "trainerDashboardUrl"),
  },
  TRAINER_DEFERRED_FEE_CLEARED: {
    subject: "Deferred platform fee cleared — Match Fit",
    preheader: "Your balance is paid in full.",
    title: "Balance cleared",
    bodyParagraphs: [
      "Your deferred platform registration fee balance is cleared. Payout withhold no longer applies.",
    ],
    textBody: "Your deferred platform fee balance is cleared.\n\n{{trainerDashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Trainer dashboard", "trainerDashboardUrl"),
  },
  CLIENT_VIP_SUBSCRIPTION_STARTED: {
    subject: "Welcome to Match Fit VIP",
    preheader: "Full platform access is unlocked.",
    title: "VIP active",
    bodyParagraphs: [
      "Your VIP subscription is active. You now have full access to matching, chat, booking, and FitHub.",
    ],
    textBody: "Your Match Fit VIP subscription is active.\n\n{{dashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open dashboard", "dashboardUrl"),
  },
  FP_DOCS_ALL_APPROVED: {
    subject: "Your Match Fit documents are approved",
    preheader: "Onboarding documents cleared.",
    title: "Documents approved",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — your required Fitness Pro documents are approved.',
      "You can continue onboarding in your dashboard. We will notify you if anything else is needed.",
    ],
    textBody:
      "Hi {{firstName}},\n\nYour required Fitness Pro documents are approved. Continue in your dashboard:\n{{trainerDashboardUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Trainer dashboard", "trainerDashboardUrl"),
  },
  FP_DOC_DENIED: {
    subject: "Action needed on your Match Fit document",
    preheader: "A document needs to be re-uploaded.",
    title: "Document not approved",
    bodyParagraphs: [
      'Hi <strong style="color:#E8EAEF">{{firstName}}</strong> — we could not approve your <strong style="color:#E8EAEF">{{docLabel}}</strong>.',
      "{{denialReason}}",
      "Upload a corrected file from your onboarding documents page.",
    ],
    textBody:
      "Hi {{firstName}},\n\nWe could not approve your {{docLabel}}.\n\n{{denialReason}}\n\nRe-upload here:\n{{docsUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Upload documents", "docsUrl"),
  },
  FP_DOCS_SUBMITTED_STAFF: {
    subject: "Fitness Pro documents ready for review",
    preheader: "New document queue item.",
    title: "Documents submitted",
    bodyParagraphs: [
      '<strong style="color:#E8EAEF">{{trainerName}}</strong> ({{trainerEmail}}) submitted documents for review.',
      "Account type: {{accountTier}} · Username: {{trainerUsername}}",
    ],
    textBody:
      "{{trainerName}} ({{trainerEmail}}) submitted FP documents.\nAccount type: {{accountTier}}\nReview: {{reviewUrl}}\n\n— Match Fit",
    ...STANDARD_CTA("Open review queue", "reviewUrl"),
  },
};

const PLACEHOLDERS: Record<TransactionalEmailKind, string[]> = {
  CLIENT_WELCOME: ["firstName", "dashboardUrl"],
  TRAINER_WELCOME: ["firstName", "trainerDashboardUrl"],
  OTP_2FA: ["code"],
  PASSWORD_RESET: ["resetUrl"],
  EMAIL_CHANGE_CONFIRM: ["confirmUrl"],
  EMAIL_CHANGE_SECURITY: ["newEmail"],
  LOGIN_SECURITY_ALERT: ["loginTime", "deviceLine", "ipLine"],
  W9_TAX_VERIFICATION: ["w9Summary"],
  CERTIFICATION_RENEWAL_REMINDER: ["certName", "expiryDate", "trainerDashboardUrl"],
  BACKGROUND_CHECK_UPDATE: ["bgStatus", "dashboardUrl"],
  BACKGROUND_CHECK_PLAN_B_INVITE_REQUEST: ["trainerName", "trainerEmail", "trainerUsername", "trainerPhone", "serviceZip", "trainerId", "confirmInviteSentUrl"],
  BACKGROUND_CHECK_PLAN_B_INVITE_SENT_TRAINER: ["firstName", "dashboardUrl"],
  BACKGROUND_CHECK_PLAN_B_REVIEW: ["trainerName", "trainerEmail", "reportId", "status", "approveUrl", "denyUrl"],
  ADMIN_REGISTRATION_REQUEST: ["adminName", "adminEmail", "adminNotes", "approveUrl", "denyUrl"],
  PURCHASE_CONFIRMATION: ["itemLabel", "amount", "trainerUsername", "referenceId", "dashboardUrl"],
  COACH_PACKAGE_SALE: ["clientUsername", "itemLabel", "amount", "trainerDashboardUrl"],
  TRAINER_PAYOUT: ["payoutAmount", "periodLabel", "trainerDashboardUrl"],
  SUBSCRIPTION_MANAGEMENT_UPDATE: ["statusLine", "detailLine", "dashboardUrl"],
  OFF_PLATFORM_VIOLATION_NOTICE: ["violationSummary"],
  BUG_REPORT_ACKNOWLEDGMENT: ["reportId"],
  NEW_CLIENT_INQUIRY: ["inquiryNote", "clientUsername", "interestsUrl"],
  BOOKING_SESSION_CONFIRMED: ["firstName", "coachName", "startLabel", "sessionDelivery", "videoPlatform", "joinUrl", "messagesThreadUrl"],
  CONTENT_MODERATION_NOTICE: ["moderationSummary", "trainerDashboardUrl"],
  PAYMENT_FAILED: ["detailLine", "dashboardUrl"],
  POLICY_UPDATE: ["policyName", "policyUrl"],
  BETA_WAITLIST_TRAINER_CONFIRM: ["firstName", "queuePosition", "supportUrl"],
  BETA_WAITLIST_CLIENT_CONFIRM: ["firstName", "queuePosition", "supportUrl"],
  BETA_WAITLIST_TRAINER_INVITE: ["firstName", "joinUrl", "reservedUsername", "slotExpiresLabel"],
  BETA_WAITLIST_CLIENT_INVITE: ["firstName", "joinUrl", "reservedUsername", "slotExpiresLabel"],
  CLIENT_MEMBERSHIP_TRIAL_STARTED: ["trialDays", "trialEndLabel", "monthlyUsd", "paymentGraceDays", "dashboardUrl"],
  CLIENT_MEMBERSHIP_TRIAL_ENDING: ["trialEndLabel", "monthlyUsd", "dashboardUrl"],
  CLIENT_PLATFORM_PAYMENT_GRACE_STARTED: ["paymentGraceDays", "paymentGraceUntilLabel", "monthlyUsd", "dashboardUrl"],
  TRAINER_REGISTRATION_FEE_RECEIPT: ["amount", "trainerDashboardUrl"],
  TRAINER_DEFERRED_FEE_GRACE_STARTED: ["graceHours", "trainerDashboardUrl"],
  TRAINER_DEFERRED_FEE_BANNED: ["supportEmail", "trainerDashboardUrl"],
  TRAINER_DEFERRED_FEE_CLEARED: ["trainerDashboardUrl"],
  CLIENT_VIP_SUBSCRIPTION_STARTED: ["dashboardUrl"],
  FP_DOCS_ALL_APPROVED: ["firstName", "trainerDashboardUrl"],
  FP_DOC_DENIED: ["firstName", "docLabel", "denialReason", "docsUrl", "trainerDashboardUrl"],
  FP_DOCS_SUBMITTED_STAFF: ["trainerName", "trainerEmail", "trainerUsername", "accountTier", "reviewUrl"],
};

export function getDefaultTransactionalEmailTemplateFields(kind: TransactionalEmailKind): TransactionalEmailTemplateFields {
  const row = DEFAULTS[kind];
  return {
    ...row,
    bodyParagraphs: [...row.bodyParagraphs],
    layout: { ...row.layout },
  };
}

export function transactionalEmailTemplatePlaceholders(kind: TransactionalEmailKind): string[] {
  return [...PLACEHOLDERS[kind]];
}
