import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSessionTrainerId } from "@/lib/session";

type W9Stored = {
  legalName?: string;
  businessName?: string;
  federalTaxClassification?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  zip?: string;
  tinType?: string;
  tin?: string;
  submittedAt?: string;
};

function maskTin(tin: string | undefined): string {
  const raw = (tin ?? "").replace(/\s/g, "");
  if (!raw) return "—";
  if (raw.length <= 4) return "*".repeat(raw.length);
  return "*".repeat(raw.length - 4) + raw.slice(-4);
}

function field(label: string, value: string): string {
  return `<div>
    <div class="label">${label}</div>
    <div class="value">${value}</div>
  </div>`;
}

export async function GET() {
  const trainerId = await getSessionTrainerId();
  if (!trainerId) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  const profile = await prisma.trainerProfile.findUnique({
    where: { trainerId },
    select: { w9Json: true },
  });

  if (!profile?.w9Json?.trim()) {
    return NextResponse.json({ error: "No W-9 on file." }, { status: 404 });
  }

  let w9: W9Stored;
  try {
    w9 = JSON.parse(profile.w9Json) as W9Stored;
  } catch {
    return NextResponse.json({ error: "W-9 data could not be read." }, { status: 500 });
  }

  const addressParts = [w9.addressLine1, w9.addressLine2].filter(Boolean).join(", ");
  const cityStateZip = [w9.city, w9.state, w9.zip].filter(Boolean).join(", ");
  const fullAddress = [addressParts, cityStateZip].filter(Boolean).join("<br>") || "—";

  const submittedDisplay = w9.submittedAt
    ? new Date(w9.submittedAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "—";

  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const tinLabel = w9.tinType ? `TIN (${w9.tinType.toUpperCase()}, Masked)` : "TIN (Masked)";
  const maskedTin = maskTin(w9.tin);

  const fieldsHtml = [
    field("Legal Name", w9.legalName ?? "—"),
    ...(w9.businessName ? [field("Business Name / Disregarded Entity Name", w9.businessName)] : []),
    field("Federal Tax Classification", w9.federalTaxClassification ?? "—"),
    field("Address", fullAddress),
    field(tinLabel, `<span style="font-family: monospace;">${maskedTin}</span>`),
    field("Date Submitted", submittedDisplay),
  ].join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Match Fit — W-9 Summary</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 680px; margin: 40px auto; color: #1a1a1a; padding: 0 20px; }
  h1 { font-size: 1.4rem; border-bottom: 2px solid #FF7E00; padding-bottom: 10px; }
  .label { font-size: 0.75rem; font-weight: bold; text-transform: uppercase; color: #888; margin-top: 18px; }
  .value { font-size: 1rem; margin-top: 4px; }
  .notice { margin-top: 40px; font-size: 0.75rem; color: #888; border-top: 1px solid #ddd; padding-top: 14px; }
</style>
</head>
<body>
<h1>Match Fit — W-9 Tax Form Summary</h1>
<p><strong>Important:</strong> This is a summary of the W-9 information on file with Match Fit. It is not an official IRS W-9 form. Match Fit will issue a 1099-NEC using this information if your earnings meet the IRS reporting threshold.</p>
${fieldsHtml}
<div class="notice">
  Generated by Match Fit on ${generatedDate}. This document is for your personal records only. Contact support@match-fit.net with questions.
</div>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": 'attachment; filename="matchfit-w9-summary.html"',
    },
  });
}
