#!/bin/bash
# SessionStart hook for Claude Code on the web.
#
# Bootstraps this repo (Next.js 16 + Prisma 7 + Postgres) so lint/tests/build
# are ready to run without Claude spending tokens rediscovering setup steps.
#
# Runs synchronously (no async mode) and only in remote (web) sessions.
# Safe to re-run: npm install is incremental, Postgres start is a no-op if
# already up, and `.env` / `prisma db push` are idempotent.
set -uo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "$CLAUDE_PROJECT_DIR" || exit 0

echo "[session-start] Installing npm dependencies..."
npm install
INSTALL_STATUS=$?
if [ "$INSTALL_STATUS" -ne 0 ]; then
  echo "[session-start] npm install failed (exit $INSTALL_STATUS) — continuing so the session still starts." >&2
fi

echo "[session-start] Ensuring local PostgreSQL (cluster 16 'main') is running..."
if command -v pg_isready >/dev/null 2>&1 && pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
  echo "[session-start] Postgres already accepting connections on 5432."
else
  sudo pg_ctlcluster 16 main start 2>&1 || echo "[session-start] pg_ctlcluster start failed or already running — continuing." >&2
  # Give the server a moment to accept connections.
  for i in $(seq 1 10); do
    if command -v pg_isready >/dev/null 2>&1 && pg_isready -h localhost -p 5432 >/dev/null 2>&1; then
      echo "[session-start] Postgres is up."
      break
    fi
    sleep 1
  done
fi

echo "[session-start] Ensuring local 'matchfit' Postgres role/database exist..."
if command -v sudo >/dev/null 2>&1 && sudo -u postgres true 2>/dev/null; then
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='matchfit'" 2>/dev/null | grep -q 1 \
    || sudo -u postgres psql -c "CREATE ROLE matchfit WITH LOGIN PASSWORD 'matchfit' CREATEDB;" >/dev/null 2>&1
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='matchfit'" 2>/dev/null | grep -q 1 \
    || sudo -u postgres psql -c "CREATE DATABASE matchfit OWNER matchfit;" >/dev/null 2>&1
else
  echo "[session-start] Cannot run psql as postgres user — skipping role/db bootstrap (may already exist)." >&2
fi

# Ensure a minimal local .env exists so prisma/db push/lint/tests have what
# they need. Never overwrite an existing .env, and never write real
# third-party secrets (Stripe/Resend/OpenAI etc. are optional and the app
# degrades gracefully without them per AGENTS.md).
if [ ! -f "$CLAUDE_PROJECT_DIR/.env" ]; then
  echo "[session-start] Creating minimal .env for local dev..."
  AUTH_SECRET_VALUE="$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
  cat > "$CLAUDE_PROJECT_DIR/.env" <<EOF
# Auto-generated by .claude/hooks/session-start.sh for local/remote dev sessions.
# Local Postgres (started by this hook via: sudo pg_ctlcluster 16 main start)
DATABASE_URL="postgresql://matchfit:matchfit@localhost:5432/matchfit"
DIRECT_URL="postgresql://matchfit:matchfit@localhost:5432/matchfit"

# Required for sessions and one-time codes (min 32 characters)
AUTH_SECRET="${AUTH_SECRET_VALUE}"

# Plain http://localhost only — never set on a public HTTPS deployment.
MATCH_FIT_COOKIE_SECURE=0
EOF
else
  echo "[session-start] .env already exists — leaving it untouched."
fi

echo "[session-start] Pushing Prisma schema to local database..."
npm run db:push
DB_PUSH_STATUS=$?
if [ "$DB_PUSH_STATUS" -ne 0 ]; then
  echo "[session-start] db:push failed (exit $DB_PUSH_STATUS). Postgres or DATABASE_URL may need attention." >&2
fi

echo "[session-start] NVG BOOT CONTRACT v2 (2026-09-02) — identical in every repo and every routine"
echo "[session-start] 1. Invoke skill nvg-operator-core — binding law. If it fails to load: stop, say so, assert nothing."
echo "[session-start] 2. select * from v_boot; on NI-Brain kxijunwgbrlfzvgkhklo — live rules, switches, open jobs, health. The one door."

echo "[session-start] Done."
exit 0
