/**
 * Generates the idempotent seed SQL for `venture_offering_dpmo` from
 * OFFERING_DPMO_SEED. Prints SQL to stdout. It never connects to a database
 * and it never sends, posts or spends anything.
 */
import { OFFERING_DPMO_SEED, resolveDpmoSupport } from "../src/lib/offering-dpmo";

const q = (v: string | null) => (v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`);

const rows = OFFERING_DPMO_SEED.map((d) => {
  const channels = JSON.stringify(d.marketing.channels).replace(/'/g, "''");
  const s = resolveDpmoSupport(d);
  return `SELECT o."id", ${q(d.sector)}, ${q(d.phase)}, ${d.marketingEnabled}, ${d.outreachEnabled},
       ${q(d.marketing.angle)}, ${q(d.marketing.proof)}, ${q(d.marketing.cta)}, ${q(d.marketing.link)},
       '${channels}'::jsonb, ${q(d.marketing.cadence)}, ${q(d.marketing.notes)},
       ${q(d.outreach.channel)}, ${q(d.outreach.opener)}, ${q(d.outreach.benefit)}, ${q(d.outreach.link)}, ${q(d.outreach.notes)},
       ${q(d.benefitLine)}, ${q(d.priceNote)},
       ${q(s.marketingLeadSource)}, ${q(s.outreachLeadSource)},
       ${q(s.phaseSwitchTrigger)}, ${q(s.jbInvolvement)}, ${q(s.sectorReconciliation)}
FROM "venture_offerings" o JOIN "ventures" v ON v."id" = o."ventureId"
WHERE v."slug" = ${q(d.ventureSlug)} AND o."slug" = ${q(d.offeringSlug)}`;
});

const cols = `"id","updatedAt","offeringId","sector","phase","marketingEnabled","outreachEnabled",
  "marketingAngle","marketingProof","marketingCta","marketingLink","marketingChannels","marketingCadence","marketingNotes",
  "outreachChannel","outreachOpener","outreachBenefit","outreachLink","outreachNotes","benefitLine","priceNote",
  "marketingLeadSource","outreachLeadSource","phaseSwitchTrigger","jbInvolvement","sectorReconciliation"`;

console.log(`-- GENERATED by scripts/generate-offering-dpmo-seed.ts. Do not hand-edit.
-- Both live switches ship FALSE for every offering. JB sets his own strategy.
INSERT INTO "venture_offering_dpmo" (${cols})
SELECT gen_random_uuid()::text, now(), s.* FROM (
${rows.join("\nUNION ALL\n")}
) AS s
ON CONFLICT ("offeringId") DO UPDATE SET
  "updatedAt" = now(),
  "sector" = EXCLUDED."sector",
  "phase" = EXCLUDED."phase",
  "marketingAngle" = EXCLUDED."marketingAngle",
  "marketingProof" = EXCLUDED."marketingProof",
  "marketingCta" = EXCLUDED."marketingCta",
  "marketingLink" = EXCLUDED."marketingLink",
  "marketingChannels" = EXCLUDED."marketingChannels",
  "marketingCadence" = EXCLUDED."marketingCadence",
  "marketingNotes" = EXCLUDED."marketingNotes",
  "outreachChannel" = EXCLUDED."outreachChannel",
  "outreachOpener" = EXCLUDED."outreachOpener",
  "outreachBenefit" = EXCLUDED."outreachBenefit",
  "outreachLink" = EXCLUDED."outreachLink",
  "outreachNotes" = EXCLUDED."outreachNotes",
  "benefitLine" = EXCLUDED."benefitLine",
  "priceNote" = EXCLUDED."priceNote",
  "marketingLeadSource" = EXCLUDED."marketingLeadSource",
  "outreachLeadSource" = EXCLUDED."outreachLeadSource",
  "phaseSwitchTrigger" = EXCLUDED."phaseSwitchTrigger",
  "jbInvolvement" = EXCLUDED."jbInvolvement",
  "sectorReconciliation" = EXCLUDED."sectorReconciliation";
-- NOTE: the two live switches are deliberately NOT in the DO UPDATE list.
-- Re-running this seed can never turn a switch on, and can never turn JB's off.
`);
